" source default file
source $VIMRUNTIME/vimrc_example.vim

" make backups go to other folder
set backupdir=~/.vim/backup//,.
set directory=~/.vim/backup//,.

" turn off undofile
set noundofile

" add indentation settings
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab smartindent

" add line numbers
set number
