" source default file
source $VIMRUNTIME/vimrc_example.vim

" make backups go to other folder
set backupdir=~/.vim/backup//,.
set directory=~/.vim/backup//,.

" turn off undofile
set noundofile

" add indentation settings
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab smartindent

" add line numbers
set number

" highlight past 80
let &colorcolumn=join(range(81,999),",")
highlight ColorColumn ctermbg=3

" prevent // autoinsertion
" http://vim.wikia.com/wiki/Disable_automatic_comment_insertion
au FileType c,cpp,scala setlocal comments-=:// comments+=f://
