" source default file
source $VIMRUNTIME/vimrc_example.vim

" make backups go to other folder
set backupdir=~/.vim/backup//,.
set directory=~/.vim/backup//,.

" turn off undofile
set noundofile

" add indentation settings
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab smartindent

" add line numbers
set number

" highlight past 80
let &colorcolumn=join(range(81,999),",")
highlight ColorColumn ctermbg=3

" prevent // autoinsertion
" (see https://stackoverflow.com/questions/4896003/
" how-do-i-stop-vim-from-auto-creating-comments-on-enter-press
inoremap <expr> <enter> getline('.') =~ '^\s*//' ? '<enter><esc>S' : '<enter>'
